### PR TITLE
Add option for disabling manual page changes by the user

### PR DESCRIPTION
**Pull request by cadivus**
When using auto scrolling, I may want to disable manual page changes by scrolling. This PR adds an option for that.

### CODE REVIEW

**Comment by edasandesu** [comment]
Thank you for the pull request👍
I'll review it!

**Comment by edasandesu** [comment]
cool!

**Comment by cadivus** [comment]
@edasandesu Thanks a lot for reviewing and merging this! Could you create a new pub release with that?

**Comment by edasandesu** [comment]
@cadivus 
Yeah! I am going to create a new publication release.
Please wait a little while for it to be completed.

**Comment by cadivus** [comment]
@edasandesu Thanks a lot, that's great!

**Comment by edasandesu** [comment]
@cadivus I have published v0.1.5!!🥳

**Pull request merged**
